package com.cms.gwt.fs.client.reflection;

/**
 * A marker interface. 
 * 
 * The concrete implementation will be generated by the extended Generator during compile time.
 */
public interface FactoryWrapper {
	// Does not contain anything in this marker interface.
}
