package com.cms.gwt.fs.client.reflection;

/**
 * Marker interface.
 * 
 * Any classes marked with this interface can be generated by the Factory class.
 */
public interface Instantiable {
	// Marker interface. This interface does not contain any methods.
}
